cp ../../cam/bootstrap.py .
cp ../../cam/cam_stack.yaml .
cp ../../cam/launch.py .
cp ../../cam/script.js .
cp ../../cam/cam_deps.bz2 .
cp ../../cam/clean_up.py .
cp ../../cam/fix_errors.py .
cp ../../cam/aws_backend.py .
cp ../../cam/cam_deps.zip .
cp ../../cam/configure.py .
cp ../../cam/index.html .
cp ../../cam/create_cases .
cp ../../cam/create_cases .
cp ../../cam/put_cases_in_queue.py .
cp ../../cam/process_results.py .
